liba{certifiable_inference}: \
  c{core/**.c} \
  c{containers/**.c} \
  h{../include/**.h}
{
  export = true
  install = true
  libs = -lm
}

if ($c.target.system == 'linux')
  liba{certifiable_inference}: lib{m}

./: liba{certifiable_inference}
