tests = exe{test_activations test_convolution test_fixed_point test_hash_basic test_hash_consistency test_matrix_reproducibility test_pooling}

exe{test_activations}: c{test_activations} ../../src/liba{certifiable_inference} $m
exe{test_convolution}: c{test_convolution} ../../src/liba{certifiable_inference} $m
exe{test_fixed_point}: c{test_fixed_point} ../../src/liba{certifiable_inference} $m
exe{test_hash_basic}:  c{test_hash_basic} ../../src/liba{certifiable_inference} $m
exe{test_hash_consistency}: c{test_hash_consistency} ../../src/liba{certifiable_inference} $m
exe{test_matrix_reproducibility}: c{test_matrix_reproducibility} ../../src/liba{certifiable_inference} $m
exe{test_pooling}: c{test_pooling} ../../src/liba{certifiable_inference} $m

$tests:
{
  c.coptions += -UNDEBUG
  test = true
}

./: $tests
